// JsFromRoutes CacheKey 3e259110e88c6791dadb4588e64c59db
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/inertia'

export default {
  restore: /* #__PURE__ */ definePathHelper('put', '/contacts/:id/restore'),
  index: /* #__PURE__ */ definePathHelper('get', '/contacts'),
  create: /* #__PURE__ */ definePathHelper('post', '/contacts'),
  new: /* #__PURE__ */ definePathHelper('get', '/contacts/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/contacts/:id/edit'),
  update: /* #__PURE__ */ definePathHelper('patch', '/contacts/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/contacts/:id'),
}
