// JsFromRoutes CacheKey 5514da204749400720d6ea05c35199a1
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/inertia'

export default {
  restore: definePathHelper('put', '/contacts/:id/restore'),
  index: definePathHelper('get', '/contacts'),
  create: definePathHelper('post', '/contacts'),
  new: definePathHelper('get', '/contacts/new'),
  edit: definePathHelper('get', '/contacts/:id/edit'),
  update: definePathHelper('patch', '/contacts/:id'),
  destroy: definePathHelper('delete', '/contacts/:id'),
}
