// JsFromRoutes CacheKey 42b41c1b7527b935e1d955ff1e8f4c5b
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/inertia'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/'),
}
