// JsFromRoutes CacheKey cc87e3eafcb846f6baada5a2ca188933
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/inertia'

export default {
  index: definePathHelper('get', '/'),
}
