// JsFromRoutes CacheKey 74bb8baaaaa1e7a8eead67f890fcfa7c
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/inertia'

export default {
  restore: definePathHelper('put', '/organizations/:id/restore'),
  index: definePathHelper('get', '/organizations'),
  create: definePathHelper('post', '/organizations'),
  edit: definePathHelper('get', '/organizations/:id/edit'),
  update: definePathHelper('patch', '/organizations/:id'),
  destroy: definePathHelper('delete', '/organizations/:id'),
}
