// JsFromRoutes CacheKey e6e73f5ddef3bf4016bad6e1ea0ae128
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/inertia'

export default {
  restore: /* #__PURE__ */ definePathHelper('put', '/organizations/:id/restore'),
  index: /* #__PURE__ */ definePathHelper('get', '/organizations'),
  create: /* #__PURE__ */ definePathHelper('post', '/organizations'),
  edit: /* #__PURE__ */ definePathHelper('get', '/organizations/:id/edit'),
  update: /* #__PURE__ */ definePathHelper('patch', '/organizations/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/organizations/:id'),
}
