// JsFromRoutes CacheKey c32f66e740f84d101026446f476ae4d2
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/inertia'

export default {
  index: definePathHelper('get', '/reports'),
}
