// JsFromRoutes CacheKey f01af5a36991b5a14f271b0ac95d8afc
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/inertia'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/reports'),
}
