// JsFromRoutes CacheKey ca47ad94fbca3ff47dae15182c9b28bf
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/inertia'

export default {
  restore: definePathHelper('put', '/users/:id/restore'),
  index: definePathHelper('get', '/users'),
  create: definePathHelper('post', '/users'),
  new: definePathHelper('get', '/users/new'),
  edit: definePathHelper('get', '/users/:id/edit'),
  update: definePathHelper('patch', '/users/:id'),
  destroy: definePathHelper('delete', '/users/:id'),
}
