// JsFromRoutes CacheKey e30615199f275f42b45e8a60cae0155c
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/inertia'

export default {
  restore: /* #__PURE__ */ definePathHelper('put', '/users/:id/restore'),
  index: /* #__PURE__ */ definePathHelper('get', '/users'),
  create: /* #__PURE__ */ definePathHelper('post', '/users'),
  new: /* #__PURE__ */ definePathHelper('get', '/users/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/users/:id/edit'),
  update: /* #__PURE__ */ definePathHelper('patch', '/users/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/users/:id'),
}
