// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Dropdown: typeof import('./components/Dropdown.vue')['default']
    ExternalLink: typeof import('./components/ExternalLink.vue')['default']
    FileInput: typeof import('./components/FileInput.vue')['default']
    FlashMessages: typeof import('./components/FlashMessages.vue')['default']
    Head: typeof import('./components/Head.ts')['default']
    Icon: typeof import('./components/Icon.vue')['default']
    InertiaLink: typeof import('./components/InertiaLink.ts')['default']
    Link: typeof import('./components/Link.vue')['default']
    LoadingButton: typeof import('./components/LoadingButton.vue')['default']
    Logo: typeof import('./components/Logo.vue')['default']
    MainMenu: typeof import('./components/MainMenu.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    Pagination: typeof import('./components/Pagination.vue')['default']
    SearchFilter: typeof import('./components/SearchFilter.vue')['default']
    SelectInput: typeof import('./components/SelectInput.vue')['default']
    TextareaInput: typeof import('./components/TextareaInput.vue')['default']
    TextInput: typeof import('./components/TextInput.vue')['default']
    TrashedMessage: typeof import('./components/TrashedMessage.vue')['default']
  }
}
