require:
  - standard

plugins:
  - standard-custom
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

inherit_gem:
  standard: config/base.yml

AllCops:
  TargetRubyVersion: 4.0
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - app/frontend/**/*
    - bin/**/*
    - node_modules/**/*
    - public/**/*
    - vendor/**/*

Rails/CreateTableWithTimestamps:
  Exclude:
    - db/schema.rb

Rails/EnvLocal:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Rails/RedirectBackOrTo:
  Enabled: false

Rails/SkipsModelValidations:
  Exclude:
    - db/migrate/20201210064113_add_service_name_to_active_storage_blobs.rb
    - spec/**/*

Rails/ToFormattedS:
  Enabled: false

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test

Rails:
  Enabled: true
  Exclude:
    - bin/**/*
    - exe/**/*
    - lib/tasks/**/*
    - Rakefile

RSpec:
  Enabled: true

RSpec/DescribeClass:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

# capybara_test_helpers performs expectations through `helper.should`.
RSpec/NoExpectationExample:
  Exclude:
    - spec/features/**/*

Style/HashSyntax:
  EnforcedStyle: ruby19
  EnforcedShorthandSyntax: always

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
