inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

inherit_mode:
  merge:
    - Exclude

AllCops:
  SuggestExtensions: false
  NewCops: enable
  TargetRubyVersion: 4.0

Layout/LineLength:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Metrics:
  Enabled: false

Naming/BlockForwarding:
  Enabled: false

Rails/EnvLocal:
  Enabled: false

Rails/RedirectBackOrTo:
  Enabled: false

Rails/ToFormattedS:
  Enabled: false

Style/ArgumentsForwarding:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/FetchEnvVar:
  Enabled: false

Style/RedundantConstantBase:
  Enabled: false

Style/SuperWithArgsParentheses:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/Lambda:
  Enabled: false

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test

Rails/SkipsModelValidations:
  Exclude:
    - spec/**/*

Rails:
  Enabled: true # enable rubocop-rails cops
  Exclude:
    - 'bin/**/*'
    - 'exe/**/*'
    - 'lib/tasks/**/*'
    - Rakefile
RSpec:
  Enabled: true # enable rubocop-rspec cops
RSpec/DescribeClass:
  Enabled: false # ignore missing comments on classes
RSpec/MultipleExpectations:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/DescribedClass:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false

# Trailing Commas
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

# Outdent Access Modifier
Layout/AccessModifierIndentation:
  EnforcedStyle: outdent
Layout/CommentIndentation:
  Exclude:
    - integration_test_helpers/**/*
