// TypesFromSerializers CacheKey 9beb9598891cfab0cf5a8a79f7bee0d8
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface ContactList {
  id: number
  city?: string
  deleted_at?: string | Date
  name: string
  phone?: string
}
