// TypesFromSerializers CacheKey 0812f99d6585e698f77af4a5d529b09e
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface ContactList {
  id: number
  city?: string
  deleted_at?: string | Date
  name: unknown
  phone?: string
}
