// TypesFromSerializers CacheKey b29e3b683fa516c817364bf089238156
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Model from '~/types/serializers/Model'

export default interface Contact {
  id: number
  name: unknown
  phone?: string
  city?: string
  deletedAt?: string | Date
  organization: Model
}
