// TypesFromSerializers CacheKey dfec2ec956c902a851f730cce4fb5b3d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Model from './Model'

export default interface Contact {
  id: number
  city?: string
  deleted_at?: string | Date
  name: unknown
  organization: Model
  phone?: string
}
