// TypesFromSerializers CacheKey ba76b4e6a55b666af772f567eb6edcc3
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface ContactForm {
  id: number
  address?: string
  city?: string
  country?: string
  deleted_at?: string | Date
  email?: string
  first_name: string
  last_name: string
  organization_id?: number
  phone?: string
  postal_code?: string
  region?: string
}
