// TypesFromSerializers CacheKey 6603c6c7add432b5823da7913388da19
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Model from './Model'

export default interface Contact {
  id: number
  city?: string
  deleted_at?: string | Date
  name: string
  organization: Model
  phone?: string
}
