// TypesFromSerializers CacheKey 45cecc4a0fdb7471602b90b3188e3f91
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface CurrentUser {
  id: number
  firstName: string
  lastName: string
  name: string
}
