// TypesFromSerializers CacheKey 51985e97277373db7a65884f00993751
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface CurrentUser {
  id: number
  first_name: string
  last_name: string
  name: string
}
