// TypesFromSerializers CacheKey 53c69d4250e53a7215d5abcb9748f11c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface Model {
  id: unknown
  name: unknown
}
