// TypesFromSerializers CacheKey 308064512f2af163e4de7f12a487a8b9
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface Model {
  id: unknown
  name: unknown
}
