// TypesFromSerializers CacheKey 543b5f3ccbf56581bfd285d9da44e593
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface Model {
  id: number
  name: string
}
