// TypesFromSerializers CacheKey 4145e606ac16c441c38933542b3d9674
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface Organization {
  id: number
  city?: string
  deleted_at?: string | Date
  name: string
  phone?: string
}
