// TypesFromSerializers CacheKey bb9594b997e6c7f3af8a57dd9a2581a9
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface OrganizationForm {
  id: number
  address?: string
  city?: string
  country?: string
  deleted_at?: string | Date
  email?: string
  name: string
  phone?: string
  postal_code?: string
  region?: string
}
