// TypesFromSerializers CacheKey 2e8eb9807a52b135c1d7722c582794c9
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface Organization {
  id: number
  name: string
  phone?: string
  city?: string
  deletedAt?: string | Date
}
