// TypesFromSerializers CacheKey ca828ad160415f1cd7f95124c6c790d9
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface User {
  id: number
  can: object
  deleted_at?: string | Date
  email: string
  name: string
  owner: boolean
  photo: string
}
