// TypesFromSerializers CacheKey 0da02609faf09309234a92c130b9478d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface User {
  id: number
  can: object
  deleted_at?: string | Date
  email: string
  name: unknown
  owner: boolean
  photo: string
}
