// TypesFromSerializers CacheKey 4273b2fb0630640832cceb35c51f18e0
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface UserForm {
  id: number
  deleted_at?: string | Date
  email: string
  first_name: string
  last_name: string
  owner: boolean
  photo: string
}
