// TypesFromSerializers CacheKey 4f1ae09139177c662e9f948b03acbe8c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface User {
  id: number
  email: string
  name: unknown
  owner: boolean
  deletedAt?: string | Date
  photo: string
  can: object
}
