// JsFromRoutes CacheKey 729771f077cad600a38f1aee29d78ecc
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/inertia'

export default {
  new: definePathHelper('get', '/login'),
  create: definePathHelper('post', '/login'),
  destroy: definePathHelper('delete', '/logout'),
}
