// JsFromRoutes CacheKey fdbdbff4cf517d9fd588f1d8564c9b0a
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/inertia'

export default {
  new: /* #__PURE__ */ definePathHelper('get', '/login'),
  create: /* #__PURE__ */ definePathHelper('post', '/login'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/logout'),
}
