// TypesFromSerializers CacheKey 48e81a2cc9972e9cda54fd77047a5337
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Model from './Model'

export default interface Contact {
  id: number
  city?: string
  deleted_at?: string | Date
  name: string
  organization: Model
  phone?: string
}
