// TypesFromSerializers CacheKey bf226414251633d6d52ba094e6cf621d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface ContactEdit {
  id: number
  address?: string
  city?: string
  country?: string
  deleted_at?: string | Date
  email?: string
  first_name: string
  last_name: string
  organization_id?: number
  phone?: string
  postal_code?: string
  region?: string
}
