// TypesFromSerializers CacheKey 6b552fb4358101f7eb87d4e443b3e7ee
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface Model {
  id: number
  name: string
}
