// TypesFromSerializers CacheKey 9bb681ffd46f0c1a6d1893f65278866d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface Model {
  id: any
  name: any
}
