// TypesFromSerializers CacheKey 8107dbb06d58864d6f8363d3ad182be5
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface Organization {
  id: number
  city?: string
  deleted_at?: string | Date
  name: string
  phone?: string
}
