// TypesFromSerializers CacheKey 6889753cdd1839b7990b0f6e7a78621d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface OrganizationContact {
  id: number
  city?: string
  deleted_at?: string | Date
  name: any
  phone?: string
}
