// TypesFromSerializers CacheKey a1dc9ed0ae8baf22c2b12736cb03c346
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface OrganizationEdit {
  id: number
  address?: string
  city?: string
  country?: string
  deleted_at?: string | Date
  email?: string
  name: string
  phone?: string
  postal_code?: string
  region?: string
}
