// TypesFromSerializers CacheKey c956d8d2fa64a3cb35444a91cbd1824c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface OrganizationContact {
  id: number
  city?: string
  deleted_at?: string | Date
  name: string
  phone?: string
}
