// TypesFromSerializers CacheKey 6dd1af41955a5efe599bda0daebd10da
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface OrganizationEdit {
  id: any
  address: any
  city: any
  country: any
  deleted_at: any
  email: any
  name: any
  phone: any
  postal_code: any
  region: any
}
