// TypesFromSerializers CacheKey c5b7fa6746e9c3fe495af656c2fe9e6a
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface UserEdit {
  id: number
  deleted_at?: string | Date
  email: string
  first_name: string
  last_name: string
  owner: boolean
  photo?: string
}
