// TypesFromSerializers CacheKey 1f38429cfdd3c031eb4d0cff7aef0045
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface UserEdit {
  id: number
  deleted_at?: string | Date
  email: string
  first_name: string
  last_name: string
  owner: boolean
  photo: any
}
