// TypesFromSerializers CacheKey cb8e65bbd56e504af7848fbbb6b3570f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface User {
  id: number
  can: any
  deleted_at?: string | Date
  email: string
  name: any
  owner: boolean
  photo: any
}
