// TypesFromSerializers CacheKey ef61b6fba7a4358ba0870b84a79b1c70
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface UserNew {
  email: string
  first_name: string
  last_name: string
  owner: boolean
}
