// TypesFromSerializers CacheKey 0a230736a8abb48b0b45725169bbeb19
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface User {
  id: number
  can: object
  deleted_at?: string | Date
  email: string
  name: string
  owner: boolean
  photo?: string
}
