// TypesFromSerializers CacheKey e7cba9e466b567739d3f0633aa8f27ee
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface UserEdit {
  id: any
  deleted_at: any
  email: any
  first_name: any
  last_name: any
  owner: any
  photo: any
}
