// TypesFromSerializers CacheKey 3ca00b945a03dd9d1c6b05aff778127e
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface UserNew {
  email: any
  first_name: any
  last_name: any
  owner: any
}
