name: Continuous integration
on: push

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        ports: ["5432:5432"]
        env:
          POSTGRES_PASSWORD: postgres

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Lint with RuboCop
        run: bundle exec rubocop --parallel

      - name: Install Yarn packages
        run: yarn install --frozen-lockfile

      - name: Lint with ESLint
        run: yarn lint

      - name: Install Playwright Chromium
        run: npx playwright install chromium

      - name: Run Tests
        env:
          DB_HOST: localhost
          DB_USER: postgres
          DB_PASSWORD: postgres
          RAILS_ENV: test
        run: |
          bundle exec rake db:prepare
          bundle exec rake test
          bundle exec rake test:system
