name: Continuous integration
on: push

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13-alpine
        ports: ["5432:5432"]
        env:
          POSTGRES_PASSWORD: postgres

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.4.1

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - uses: actions/setup-node@v2
        with:
          cache: 'pnpm'
          node-version: '16'

      - run: pnpm install --frozen-lockfile

      - name: Lint with RuboCop
        run: bundle exec rubocop --parallel

      - name: Lint with ESLint
        run: pnpm lint

      - name: Run Tests
        env:
          DB_HOST: localhost
          DB_USER: postgres
          DB_PASSWORD: postgres
          RAILS_ENV: test
        run: |
          bundle exec rake db:prepare
          bundle exec rake test
          bundle exec rake test:system
